language: java
jdk:
 - oraclejdk8
 
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: gentle-harbor-69465
